---
title: "Final Project final"
author: "Jiahao Chen"
date: "2021/12/8"
output: html_document
---




## R Markdown

```{r}

library(tseries) 
library(outliers)
library(zoo) 
library(dygraphs)
library(fPortfolio)
library(quantmod)
library(RiskPortfolios)  
library(ggplot2)
library(dplyr)
library(xts)
library(data.table)
library(broom)
library(plyr)
library(dplyr)
library(quantmod)
library(TTR)
library(dygraphs)#Can't use in RMD but use in R script
library(forecast)

```

# Stock Prediction

```{r}
#ARIMA model
getSymbols("AAPL",src = "yahoo")
AAPL_rawdata<-AAPL
AAPL<-xts(AAPL_rawdata$AAPL.Adjusted)%>%as.zoo()
AAPL<-window(AAPL,start = "2010-12-07",end = "2021-12-07")
chartSeries(AAPL_rawdata)
addMACD()

adf.test(AAPL)#P is higher
AAPL_clean<-na.omit(AAPL)
AAPL_clean<-diff(log(AAPL_clean))
AAPL_clean<-na.omit(AAPL_clean)
AAPL_clean<-na.omit(AAPL_clean)
ggtsdisplay(AAPL)
ggtsdisplay(AAPL_clean)
adf.test(AAPL_clean)
```


```{r}
#Model creation for long term
ts_price_predicted<-data.frame()
ts_train<-window(AAPL_clean,end = index(AAPL_clean[length(AAPL_clean)-300]))
best_model<-auto.arima(ts_train)
checkresiduals(best_model)

model_fitted<-Arima(ts_train,c(best_model$arma[1],0,best_model$arma[2]))
prediction<-forecast(model_fitted,h=300,level = 99)
basepp<-as.numeric(AAPL[index(tail(ts_train,1))])
abc<-as.numeric(prediction$mean)
abc[1]

for(i in 1:300){
  basepp<-exp(abc[i])*basepp
  ts_price_predicted<-rbind(ts_price_predicted,basepp)
}
names(ts_price_predicted)<-c("Predicted adjclose")
ts_price_predicted<-xts(ts_price_predicted,order.by = as.Date(index(tail(AAPL,300))))%>%as.zoo()
ts_error<-tail(AAPL,300)-ts_price_predicted
#dygraph(merge(ts_price_predicted,tail(AAPL,300)))
names(ts_error)<-c("error")
par(mfrow=c(1,1))
barplot(ts_error,main="Forecast period single-day error")
summary(ts_error)
```


```{r}
ts_price_predicted<-data.frame()
for(k in 300:1){
  ts_train<-window(AAPL_clean,end = index(AAPL_clean[length(AAPL_clean)-k]))
  best_model<-auto.arima(ts_train)
  model_fitted<-Arima(ts_train,c(best_model$arma[1],0,best_model$arma[2]))
  prediction<-forecast(model_fitted,h=1)
  cat("Train data",as.character(index(tail(ts_train,1))),"before all data","\n","Predicting",as.character(index(AAPL_clean)[length(AAPL_clean)-k+1]),"data\n",sep = "")
  base_price<-as.numeric(AAPL[index(tail(ts_train,1))])
  price_predicted<-exp(as.numeric(prediction$mean))*base_price
  ts_price_predicted<-rbind(ts_price_predicted,price_predicted)
}
names(ts_price_predicted)<-c("Predicted adjclose")
ts_price_predicted<-xts(ts_price_predicted,order.by = as.Date(index(tail(AAPL,300))))%>%as.zoo()
#dygraph(merge(ts_price_predicted,tail(AAPL,300)))
ts_error<-tail(AAPL,300)-ts_price_predicted
names(ts_error)<-c("error")
par(mfrow=c(1,1))
barplot(ts_error,main="Forecast period single-day error")
summary(ts_error)

```


# Opitimal Portofolio

```{r}
#AAPL
getSymbols("AAPL",src = "yahoo")
AAPL<-xts(AAPL$AAPL.Adjusted)%>%as.zoo()
AAPL<-window(AAPL, start = "2018-12-7",end = "2021-12-7")

#ORCL
getSymbols("ORCL",src = "yahoo")
ORCL<-xts(ORCL$ORCL.Adjusted)%>%as.zoo()
ORCL<-window(ORCL, start = "2018-12-7",end = "2021-12-7")

#JNJ
getSymbols("JNJ",src = "yahoo")
JNJ<-xts(JNJ$JNJ.Adjusted)%>%as.zoo()
JNJ<-window(JNJ, start = "2018-12-7",end = "2021-12-7")

#MSFT
getSymbols("MSFT",src = "yahoo")
MSFT<-xts(MSFT$MSFT.Adjusted)%>%as.zoo()
MSFT<-window(MSFT, start = "2018-12-7",end = "2021-12-7")

#GOOG
getSymbols("GOOG",src = "yahoo")
GOOG<-xts(GOOG$GOOG.Adjusted)%>%as.zoo()
GOOG<-window(GOOG, start = "2018-12-7",end = "2021-12-7")


#AMZN
getSymbols("AMZN",src = "yahoo")
AMZN<-xts(AMZN$AMZN.Adjusted)%>%as.zoo()
AMZN<-window(AMZN, start = "2018-12-7",end = "2021-12-7")



#JPM
getSymbols("JPM",src = "yahoo")
JPM<-xts(JPM$JPM.Adjusted)%>%as.zoo()
JPM<-window(JPM, start = "2018-12-7",end = "2021-12-7")

#CSCO
getSymbols("CSCO",src = "yahoo")
CSCO<-xts(CSCO$CSCO.Adjusted)%>%as.zoo()
CSCO<-window(CSCO, start = "2018-12-7",end = "2021-12-7")


#HD
getSymbols("HD",src = "yahoo")
HD<-xts(HD$HD.Adjusted)%>%as.zoo()
HD<-window(HD, start = "2018-12-7",end = "2021-12-7")



#HON
getSymbols("HON",src = "yahoo")
HON<-xts(HON$HON.Adjusted)%>%as.zoo()
HON<-window(HON, start = "2018-12-7",end = "2021-12-7")

```

```{r}
Myportfolio<-merge(AAPL,AMZN,CSCO,GOOG,HD,HON,JPM,ORCL,MSFT,JNJ)
names(Myportfolio)<-c("AAPL","AMZN","CSCO","GOOG","HD","HON","JPM","ORCL","MSFT","JNJ")
#dygraph(Myportfolio)

```

# Data clean and return series
```{r}
DataClean <- function(MyPortfolio){
 #
  table(is.na(MyPortfolio))
  MyPortfolio<-MyPortfolio[complete.cases(MyPortfolio), ] 
  table(is.na(MyPortfolio))
  
  #
  stocknames<-names(MyPortfolio)
  #
  number<- as.character(sprintf("%03d",1:ncol(MyPortfolio)))
  new_stockname <- paste("r_",number,sep="")
  
  #
  for (m in 1:ncol(MyPortfolio)) {
    assign(new_stockname[m],
           diff(log(MyPortfolio[,m]))[abs(outliers::scores(diff(log(MyPortfolio[,m]))))<=5])
                                  }
  #
  RSeries <- cbind(r_001,r_002)
  for (i in 3:ncol(MyPortfolio)){
   temp <-get(new_stockname[i])
   RSeries <- cbind(RSeries,temp)
  }
  #
  table(is.na(RSeries))
  RSeries<-RSeries[complete.cases(RSeries), ] 
  table(is.na(RSeries))
  #
  names(RSeries) <- stocknames
  return(RSeries)
}

```


```{r}
#Yearly Return
RPortfolio<-DataClean(MyPortfolio = Myportfolio)
for(i in 1:ncol(RPortfolio)){
  RPortfolio[,i]<-RPortfolio[,i]*250
}
#dygraph(RPortfolio)
```

# Monte Carlo
```{r}
sta_por <- data.frame()
  for (i in 1:ncol(RPortfolio)) {
    sta_por <- rbind.data.frame(sta_por,data.frame(names(RPortfolio)[i],
                                                   mean(RPortfolio[,i]),
                                                   sd(RPortfolio[,i])))
  }
  names(sta_por)<- c("Tickets","Return","Standard Distribution")
  sta_por
```


```{r}
  returnPort<-colMeans(RPortfolio)
  riskPort<-cov(RPortfolio)
  w <- matrix(1,ncol=ncol(RPortfolio),nrow=1)
  mean_disv <- as.matrix(data.frame(colMeans(RPortfolio),colSds(RPortfolio)))
  n <- 20000
  for (i in 1:n){
    w<-c(runif(ncol(RPortfolio),0,1))
    w<-w/sum(w)
    
    mean_disv<-rbind(mean_disv,c(t(w)%*%returnPort,sqrt(t(w)%*%riskPort%*%w)))
  }

```




```{r}
plot(mean_disv[,2],mean_disv[,1],type="p",col="Royalblue",cex = 0.2,xlab = "σ",
ylab = "μ")
```


```{r}
  specPort<-portfolioSpec()
  #3 years
  setRiskFreeRate(specPort)<- 0.0099
  setNFrontierPoints(specPort) <- 500
  Frontera <- portfolioFrontier(as.timeSeries(RPortfolio),spec=specPort )
  plot(Frontera,risk="cov",c(1,2,3,7,8))
```



```{r}
#
PortfolioMinRisk<-minriskPortfolio(as.timeSeries(RPortfolio),spec=specPort, constraints = "LongOnly")
PortfolioMinRisk@portfolio@portfolio$weights
df <- data.frame(weights = as.numeric(PortfolioMinRisk@portfolio@portfolio$weights)*100, 
                 StockName = names(PortfolioMinRisk@portfolio@portfolio$weights))
df$StockName<-as.factor(df$StockName)
df$StockNameP <-as.factor(paste(df$StockName,round(df$weights,2),"%",sep=" "))
ggplot(df, aes(x = "", y = weights, fill = StockNameP)) + 
geom_bar(stat = "identity") + 
coord_polar(theta = "y") 
df <- df[,-3]
PortfolioMinRisk
```


```{r}
PortfolioMaxTan<-tangencyPortfolio(as.timeSeries(RPortfolio),spec=specPort, constraints = "LongOnly")
PortfolioMaxTan@portfolio@portfolio$weights

df2 <- data.frame(weights = as.numeric(PortfolioMaxTan@portfolio@portfolio$weights)*100, 
                 StockName = names(PortfolioMaxTan@portfolio@portfolio$weights))
df2$StockName<-as.factor(df2$StockName)
df2$StockNameP <-as.factor(paste(df2$StockName,round(df2$weights,2),"%",sep=" "))
ggplot(df2, aes(x = "", y = weights, fill = StockNameP)) + 
geom_bar(stat = "identity") + 
coord_polar(theta = "y") 
df2 <- df2[,-3]
```


